[project]
icon = "https://raw.githubusercontent.com/snowcrystals/.github/main/logo.png"
icon_width = "100px"
version = "0.0.1"

[variables]
information = "To use this config, create a `.prettierrc.js` file and import it like so: `module.exports = require('@snowcrystals/prettier-config');`"
installation = "```\nnpm i -D @snowcrystals/prettier-config\nyarn add -D @snowcrystals/prettier-config```"
